services:

  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: appdaf
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    container_name: nginxdaf
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - appnet

  postgres:
    image: postgres:15
    container_name: pgdaf
    restart: always
    environment:
      POSTGRES_DB: dafdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
