version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: appdaf_php
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: pgdbDaf
      DB_USER: pguserDaf
      DB_PASSWORD: pgpassword
    volumes:
      - .:/var/www/html  
      - ./public:/var/www/html/public 
    networks:
      - backend
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: appdaf_nginx
    depends_on:
      - php
    ports:
      - "8081:80"
    volumes:
      - ./public:/var/www/html/public
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  postgres:
    container_name: postgresDaf
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: pgdbDaf
      POSTGRES_USER: pguserDaf
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    container_name: pgadminDaf
    image: dpage/pgadmin4
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend

volumes:
  pg_data:
  pgadmin_data:

networks:
  backend:
