# Configuration des services AppDAF
services:
  # Repositories
  repositories:
    CitoyenRepository:
      class: App\Repository\CitoyenRepository
      singleton: true
    
  # Services
  services:
    CitoyenService:
      class: App\Service\CitoyenService
      dependencies:
        - CitoyenRepository
        - LoggerService
      singleton: true
    
    LoggerService:
      class: App\Service\LoggerService
      singleton: true
  
  # Controllers
  controllers:
    CitoyenController:
      class: App\Controller\CitoyenController
      dependencies:
        - CitoyenService
      singleton: true

# Configuration base de données
database:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5433}
  name: ${DB_NAME:pgdbDaf}
  user: ${DB_USER:pguserDaf}
  password: ${DB_PASSWORD:pgpassword}

# Configuration API
api:
  base_url: ${API_BASE_URL:http://localhost:8081}
  version: v1
  cors:
    enabled: true
    origins: ['*']
    methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    headers: ['Content-Type', 'Authorization']
